spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teste_dsa
    username: postgres
    password: 121314
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

